### ISSUE TITLE
IObjectEvent and ObjectEvent have moved

### ISSUE THREAD

**Issue by gogobd** [bluedynamics/yafowil.plone#32]
IObjectEvent and ObjectEvent have moved from zope.component.interfaces to zope.ingterface.interfaces

**Comment by avoinea** [comment]
@jensens This became a **blocker** with Plone 6.0.0a4:

```
Traceback (most recent call last):

  File "/app/lib/python3.9/site-packages/zope/configuration/xmlconfig.py", line 391, in endElementNS

    self.context.end()

  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 704, in end

    self.stack.pop().finish()

  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 868, in finish

    args = toargs(context, *self.argdata)

  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 1687, in toargs

    args[str(name)] = field.fromUnicode(s)

  File "/app/lib/python3.9/site-packages/zope/configuration/fields.py", line 269, in fromUnicode

    v = vt.fromUnicode(s)

  File "/app/lib/python3.9/site-packages/zope/configuration/fields.py", line 172, in fromUnicode

    value = self.context.resolve(name)

  File "/app/lib/python3.9/site-packages/zope/configuration/config.py", line 226, in resolve

    __import__(mname)

  File "/app/lib/python3.9/site-packages/yafowil/plone/autoform/form.py", line 34, in <module>

    from yafowil.plone.autoform.events import ImmediateAddedEvent

  File "/app/lib/python3.9/site-packages/yafowil/plone/autoform/events.py", line 2, in <module>

    from zope.component.interfaces import IObjectEvent

ImportError: cannot import name 'IObjectEvent' from 'zope.component.interfaces' (/app/lib/python3.9/site-packages/zope/component/interfaces.py)
```

**Comment by avoinea** [comment]
@jensens Can we have a fix and release of this? `pas.plugins.ldap` depends on this add-on and it doesn't work anymore with Plone >= 6.0.0a4
