### ISSUE TITLE
traceback on instance startup after updating yafowil packages (plone6 bootstrap5) from conestack

### ISSUE THREAD

**Issue by petschki** [bluedynamics/yafowil.plone#34]
maybe someone can give me a hint, whats going wrong here?

```
Traceback (most recent call last):
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/xmlconfig.py", line 391, in endElementNS
    self.context.end()
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/config.py", line 704, in end
    self.stack.pop().finish()
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/config.py", line 868, in finish
    args = toargs(context, *self.argdata)
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/config.py", line 1687, in toargs
    args[str(name)] = field.fromUnicode(s)
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/fields.py", line 172, in fromUnicode
    value = self.context.resolve(name)
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/zope.configuration-4.4.0-py3.7.egg/zope/configuration/config.py", line 226, in resolve
    __import__(mname)
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/srcaddons/yafowil.plone/src/yafowil/plone/examples/view.py", line 9, in <module>
    import yafowil.loader  # noqa  # loads registry
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/srcaddons/yafowil/src/yafowil/loader.py", line 15, in <module>
    for ep, cb in yafowil.utils.get_plugins('register'):
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/srcaddons/yafowil/src/yafowil/utils.py", line 36, in get_plugins
    cb = ep.load()
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/setuptools-54.0.0-py3.7.egg/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/Volumes/WORKSPACE2/kinderdorf_plone5/eggs/setuptools-54.0.0-py3.7.egg/pkg_resources/__init__.py", line 2460, in resolve
    raise ImportError(str(exc)) from exc
ImportError: module 'yafowil.bootstrap' has no attribute 'configure'
```

/cc @rnixx @jensens

**Comment by rnixx** [comment]
bootstrap-plone6 branch of this package in combination with 2.0 branch of yafowil.bootstrap should do the trick

**Comment by petschki** [comment]
works! thanks
